//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Inquiry
{
    public int Id { get; set; }
    public string email { get; set; }
    public string companyName { get; set; }
    public string category { get; set; }
    public string message { get; set; }
}

public partial class Payment
{
    public int Id { get; set; }
    public Nullable<int> userId { get; set; }
    public Nullable<int> productId { get; set; }
    public Nullable<int> planId { get; set; }
    public string quantity { get; set; }
    public string totalPrice { get; set; }
    public string paymentType { get; set; }
    public string datePayment { get; set; }

    public virtual Plan Plan { get; set; }
    public virtual Product Product { get; set; }
    public virtual User User { get; set; }
}

public partial class Plan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Plan()
    {
        this.Payments = new HashSet<Payment>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
    public string description_2 { get; set; }
    public string description_3 { get; set; }
    public string Price { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Payment> Payments { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.Payments = new HashSet<Payment>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
    public string price { get; set; }
    public string image1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Payment> Payments { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Payments = new HashSet<Payment>();
    }

    public int Id { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public string companyName { get; set; }
    public string fullName { get; set; }
    public string country { get; set; }
    public string userType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Payment> Payments { get; set; }
}
